FROM ruby:2.5.1
# RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

ARG DEBIAN_FRONTEND=noninteractive

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash - \
    && apt-get update -qq \
    && apt-get install -y build-essential dialog apt-utils \
    && apt-get install -y nodejs
# yarn
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -\
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get install -y yarn

# Set an environment variable where the Rails app is installed to inside of Docker image
ENV RAILS_ROOT /var/www/rails_app
ENV RAILS_ENV='production'
ENV RACK_ENV='production'

RUN mkdir -p $RAILS_ROOT
# Set working directory
WORKDIR $RAILS_ROOT
# Adding gems
COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock
RUN bundle install --jobs 20 --retry 5 --without development test
# Adding project files
COPY . .
# SECRET_KEY_BASE is setter after build inside prod.env file
# but gem devise needs SECRET_KEY_BASE, so we set it
RUN bundle exec rake assets:precompile SECRET_KEY_BASE=x
EXPOSE 3000
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]