FROM nginx:1.15.3-alpine

RUN apk add --update --no-cache \
    apache2-utils

# establish where Nginx should look for files
ENV RAILS_ROOT /rails_app
WORKDIR $RAILS_ROOT
# copy over static assets
COPY public public/
# Copy Nginx config template
COPY docker/web/nginx.conf /etc/nginx/nginx.conf

EXPOSE 80
# Use the "exec" form of CMD so Nginx shuts down gracefully on SIGTERM (i.e. `docker stop`)
CMD [ "nginx", "-g", "daemon off;" ]